language: c
 
before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs mono-dmcs > /dev/null
  - sudo apt-get install nunit-console
  - sudo apt-get install mono-complete
  - sudo apt-get install libmono-system4.0-cil
  - mozroots --import --sync
  - mv -f .nuget/NuGet.mono.targets .nuget/NuGet.targets
  - export EnableNuGetPackageRestore=true
  
script:
  - xbuild VirtualObjects.sln
  - nunit-console ./VirtualObjects.Tests/bin/Debug/VirtualObjects.Tests.dll
