using System.IO;
using FluentAssertions;
using Machine.Specifications;
using VirtualObjects.Config;
using VirtualObjects.Scaffold;
using VirtualObjects.Tests.Models.Northwind;

namespace VirtualObjects.Tests.Config
{


    [Subject(typeof (IMapper)), Tags("EntityInfo Mapper")]
    public class When_mapping_the_employee_entity : SpecsUtilityBelt
    {
        Because of = () => { EmployeeEntityInfo = Mapper.Map<Employee>(); };

        It should_not_be_null = 
            () => EmployeeEntityInfo.Should().NotBeNull();
        
        It should_have_a_matching_dll = 
            () => File.Exists("AutoGenerated\\Internal_Builder_Employee.dll").Should().BeTrue();

        It should_be_able_to_create_entities = 
            () => EmployeeEntityInfo.EntityFactory().Should().NotBeNull();

        It should_be_able_to_create_proxy = 
            () => EmployeeEntityInfo.EntityProxyFactory(Session).Should().NotBeNull();

#if DEBUG
        It should_have_a_cs_file = () => File.Exists("Internal_Builder_Employee.dll.cs");
#endif
        
        static IEntityInfo EmployeeEntityInfo;
    }

    [Subject(typeof (IMapper)), Tags("EntityInfo Mapper")]
    public class When_mapping_the_foreignkey_entity : SpecsUtilityBelt
    {
        Because of = () => { ForeignKeyEntityInfo = Mapper.Map<VirtualObjectsHelper.ForeingKey>(); };

        It should_not_be_null =
            () => ForeignKeyEntityInfo.Should().NotBeNull();

        It should_have_a_matching_dll =
            () => File.Exists("AutoGenerated\\Internal_Builder_ForeignKey.dll").Should().BeTrue();

        It should_be_able_to_create_entities =
            () => ForeignKeyEntityInfo.EntityFactory().Should().NotBeNull();

        It should_be_able_to_create_proxy =
            () => ForeignKeyEntityInfo.EntityProxyFactory(Session).Should().NotBeNull();

        static IEntityInfo ForeignKeyEntityInfo;
    }
}