using System.IO;
using System.Linq;
using FluentAssertions;
using Machine.Specifications;
using VirtualObjects.Config;
using VirtualObjects.Queries;
using VirtualObjects.Tests.Models.Northwind;

namespace VirtualObjects.Tests.Config
{

    public abstract class SpecsUtilityBelt
    {
        Establish context = () =>
        {
            var ioc = new NinjectContainer(new SessionConfiguration { }, "northwind");

            //ConnectionManager = ioc.Get<IConnection>();
            //Translator = ioc.Get<IQueryTranslator>();
            //QueryProvider = ioc.Get<IQueryProvider>();
            //SessionContext = ioc.Get<SessionContext>();

            Session = new Session(ioc);

            Mapper = ((InternalSession)Session.InternalSession).Mapper;
        };

        protected static IMapper Mapper;
        protected static Session Session;
    }

    [Subject(typeof (IMapper)), Tags("EntityInfo Mapper")]
    public class When_mapping_the_employee_entity : SpecsUtilityBelt
    {
        Because of = () => { EmployeeEntityInfo = Mapper.Map<Employee>(); };

        It should_not_be_null = 
            () => EmployeeEntityInfo.Should().NotBeNull();
        
        It should_have_a_matching_dll = 
            () => File.Exists("AutoGenerated\\Internal_Builder_Employee.dll").Should().BeTrue();

        It should_be_able_to_create_entities = 
            () => EmployeeEntityInfo.EntityFactory().Should().NotBeNull();

        It should_be_able_to_create_proxy = 
            () => EmployeeEntityInfo.EntityProxyFactory(Session).Should().NotBeNull();

#if DEBUG
        It should_have_a_cs_file = () => File.Exists("Internal_Builder_Employee.dll.cs");
#endif
        
        static IEntityInfo EmployeeEntityInfo;
    }

}